/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enabled OAuth providers available for sign-in */
        get: operations["AuthController_getEnabledProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session's user identity */
        get: operations["AuthController_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OAuth sign-up flow via invite token */
        get: operations["AuthController_join"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signOut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CsrfController_getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions, optionally filtered by user (admin only) */
        get: operations["SubscriptionController_listAll"];
        put?: never;
        /** Subscribe to a service */
        post: operations["SubscriptionController_subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions for the current user */
        get: operations["SubscriptionController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a subscription by id (admin only) */
        get: operations["SubscriptionController_getById"];
        put?: never;
        post?: never;
        /** Cancel a subscription */
        delete: operations["SubscriptionController_delete"];
        options?: never;
        head?: never;
        /** Update subscription state — enabled and/or autoRenew (admin only) */
        patch: operations["SubscriptionController_update"];
        trace?: never;
    };
    "/api/subscriptions/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew a subscription by 30 days (admin only) */
        post: operations["SubscriptionController_renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the service account password (subscription owner only) */
        post: operations["SubscriptionController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{id}/auto-renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle auto-renew for the subscription owner */
        patch: operations["SubscriptionController_setAutoRenew"];
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all invites (admin only) */
        get: operations["InviteController_list"];
        put?: never;
        /** Generate an invite token (admin only) */
        post: operations["InviteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an invite (admin only) */
        delete: operations["InviteController_delete"];
        options?: never;
        head?: never;
        /** Revoke an invite (admin only) */
        patch: operations["InviteController_update"];
        trace?: never;
    };
    "/api/users/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user statistics */
        get: operations["UserController_getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["UserController_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy the current user's avatar image */
        get: operations["UserController_getAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by ID */
        get: operations["UserController_getUser"];
        put?: never;
        post?: never;
        /** Delete a user account (soft or hard) */
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        /** Update a user account state — enabled/admin (admin only) */
        patch: operations["UserController_updateUser"];
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all services (admin only) */
        get: operations["ServiceController_list"];
        /** Create a service (admin only). Only REFERENCED and NONE account types are accepted. */
        put: operations["ServiceController_create"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update service state — enabled, imageUrl (admin only) */
        patch: operations["ServiceController_update"];
        trace?: never;
    };
    "/api/services/{slug}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List external accounts for an integrated service (admin only) */
        get: operations["ServiceController_listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all OAuth providers (admin only) */
        get: operations["OAuthProviderController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth-providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update OAuth provider state — enabled (admin only) */
        patch: operations["OAuthProviderController_update"];
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List application logs (admin only) */
        get: operations["LogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all task configurations with current status */
        get: operations["TaskController_listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task configuration (hot-reloads immediately) */
        patch: operations["TaskController_updateTask"];
        trace?: never;
    };
    "/api/tasks/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a scheduled task */
        post: operations["TaskController_startTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a scheduled task */
        post: operations["TaskController_stopTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a task immediately, regardless of its enabled state or schedule */
        post: operations["TaskController_runTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active sessions (admin only) */
        get: operations["SessionController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session configuration (admin only) */
        get: operations["SessionController_getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update session configuration (admin only) */
        patch: operations["SessionController_updateConfig"];
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a session (admin only) */
        delete: operations["SessionController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregate admin dashboard statistics */
        get: operations["DashboardController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_signIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_error"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_home"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/oauth-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminOAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/scheduled-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminScheduledTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_adminSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientRouteController_notFound"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionResponseDto: {
            /** Format: uuid */
            id: string;
            username: string;
            isAdmin: boolean;
            avatarUrl: string | null;
        };
        SubscriptionCreateRequestDto: {
            serviceId: number;
            serviceUsername: string;
            email?: string;
            servicePassword: string;
            confirmServicePassword: string;
            autoRenew: boolean;
        };
        SubscriptionResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            serviceId: number;
            /** @description External account username; null when the service has no account */
            username: string | null;
            /** @enum {string} */
            status: "provisioning" | "active" | "failed" | "cancelling" | "cancelled" | "expired" | "disabling" | "disabled" | "enabling";
            autoRenew: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            provisionedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            /** @description The subscribing user's HomeGate username (admin listings only) */
            userUsername?: string;
            /** @description The subscribing user's email (admin listings only) */
            userEmail?: string;
            /** @description The subscribed-to service's display name (admin listings only) */
            serviceName?: string;
        };
        SubscriptionPatchRequestDto: {
            enabled?: boolean;
            autoRenew?: boolean;
        };
        SubscriptionDeleteRequestDto: {
            /** @description Immediately delete the external account instead of cancelling auto-renew */
            immediate?: boolean;
        };
        SubscriptionPasswordResetDto: {
            newPassword: string;
            confirmPassword: string;
        };
        SubscriptionAutoRenewDto: {
            autoRenew: boolean;
        };
        InviteAccountDto: {
            serviceName: string;
            username?: string;
            email?: string;
            accountId?: string;
        };
        CreateInviteRequestDto: {
            email?: string;
            expiresInDays: number;
            isAdmin?: boolean;
            accounts?: components["schemas"]["InviteAccountDto"][];
        };
        InviteAccountResponseDto: {
            serviceName: string;
            username?: string;
            email?: string;
            accountId?: string;
        };
        InviteResponseDto: {
            id: string;
            email?: string;
            isAdmin: boolean;
            expiresAt: string;
            createdAt: string;
            usedAt?: string;
            revokedAt?: string;
            revokedReason?: string;
            createdByUsername?: string;
            usedByUsername?: string;
            revokedByUsername?: string;
            accounts?: components["schemas"]["InviteAccountResponseDto"][];
        };
        CreateInviteResponseDto: {
            rawToken: string;
            invite: components["schemas"]["InviteResponseDto"];
        };
        InvitePatchRequestDto: {
            revoked?: boolean;
            email?: string;
            /** Format: date-time */
            expiresAt?: string;
            isAdmin?: boolean;
        };
        UserStatusCountDto: {
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "DISABLED" | "DELETED";
            count: number;
        };
        UserStatsResponseDto: {
            /**
             * @description Total number of users
             * @example 42
             */
            total: number;
            /** @description User counts grouped by status */
            byStatus: components["schemas"]["UserStatusCountDto"][];
        };
        UserResponseForAdminDto: {
            id: string;
            email: string;
            username: string;
            firstName: string;
            lastName: string;
            isAdmin: boolean;
            avatarUrl?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "DISABLED" | "DELETED";
            /** Format: date-time */
            createdAt: string;
        };
        UserPatchRequestDto: {
            enabled?: boolean;
            admin?: boolean;
        };
        UserDeleteRequestDto: {
            /** @description Permanently delete the account. Ignored for non-admin callers. */
            hard?: boolean;
        };
        /** @enum {string} */
        AccountType: "MANAGED" | "REFERENCED" | "NONE";
        /** @enum {string} */
        IntegrationProvider: "jellyfin" | "immich";
        ServiceRequiredInputsDto: {
            username: boolean;
            password: boolean;
            email: boolean;
            displayName: boolean;
        };
        ServiceResponseDto: {
            id: number;
            name: string;
            slug: string;
            enabled: boolean;
            accountType: components["schemas"]["AccountType"];
            integrationProvider: components["schemas"]["IntegrationProvider"] | null;
            /** @description Service supplying the account for a REFERENCED service */
            accountSourceServiceId: number | null;
            /** @description Whether all users may subscribe unless overridden */
            defaultAllowed: boolean;
            url?: string | null;
            imageUrl?: string | null;
            /** @description Credentials the signup form must collect; absent when nothing is provisioned */
            requiredInputs?: components["schemas"]["ServiceRequiredInputsDto"];
        };
        /**
         * @description MANAGED is rejected: it requires a built-in integration provider
         * @enum {string}
         */
        CreatableAccountType: "REFERENCED" | "NONE";
        ServicePutRequestDto: {
            /** @description URL-safe identifier, e.g. "jellyseerr" */
            slug: string;
            name: string;
            /** @description MANAGED is rejected: it requires a built-in integration provider */
            accountType: components["schemas"]["CreatableAccountType"];
            /** @description Required for REFERENCED; must name a MANAGED service */
            accountSourceServiceId?: number | null;
            enabled?: boolean;
            defaultAllowed?: boolean;
            url?: string | null;
            imageUrl?: string | null;
        };
        ServicePatchRequestDto: {
            enabled?: boolean;
            url?: string | null;
            imageUrl?: string | null;
        };
        ExternalAccountResponseDto: {
            id: string;
            username: string;
            isActive: boolean;
            isAdmin: boolean;
        };
        OAuthProviderResponseDto: {
            id: number;
            /** @enum {string} */
            name: "google";
            enabled: boolean;
        };
        OAuthProviderPatchRequestDto: {
            enabled?: boolean;
        };
        LogResponseDto: {
            id: number;
            userId?: string;
            sessionId?: string;
            correlationId?: string;
            /** @enum {string} */
            logLevel: "verbose" | "debug" | "log" | "warn" | "error" | "fatal";
            context?: string;
            message: string;
            stackTrace?: string;
            /** Format: date-time */
            createdAt: string;
        };
        TaskConfigResponseDto: {
            name: string;
            enabled: boolean;
            runOnStartup: boolean;
            cronExpression: string;
            isActive: boolean;
            /** Format: date-time */
            lastAttemptedRunAt?: string | null;
            /** Format: date-time */
            lastSuccessfulRunAt?: string | null;
            /** @description Duration in milliseconds of the last attempted run */
            lastRunDurationMs?: number | null;
        };
        UpdateTaskConfigDto: {
            enabled?: boolean;
            runOnStartup?: boolean;
            cronExpression?: string;
        };
        AdminSessionResponseDto: {
            id: string;
            userId?: string | null;
            username?: string | null;
            provider?: string | null;
            ipAddress?: string | null;
            device?: string | null;
            browser?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        SessionConfigResponseDto: {
            /** @description Maximum concurrent sessions allowed per user; oldest are evicted at login */
            maxPerUser: number;
        };
        UpdateSessionConfigDto: {
            maxPerUser: number;
        };
        DashboardUsersDto: {
            total: number;
            active: number;
            pending: number;
            disabled: number;
        };
        DashboardSessionsDto: {
            active: number;
            expired: number;
        };
        DashboardSubscriptionsDto: {
            total: number;
            active: number;
        };
        DashboardTasksDto: {
            total: number;
            /** @description Tasks whose most recent run failed */
            failing: number;
        };
        DashboardErrorDto: {
            id: number;
            message: string;
            context: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardStatsResponseDto: {
            users: components["schemas"]["DashboardUsersDto"];
            sessions: components["schemas"]["DashboardSessionsDto"];
            subscriptions: components["schemas"]["DashboardSubscriptionsDto"];
            tasks: components["schemas"]["DashboardTasksDto"];
            recentErrors: components["schemas"]["DashboardErrorDto"][];
        };
        PaginationRequestDto: {
            /** @default 50 */
            take: number;
            /** @default 0 */
            skip: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getEnabledProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    AuthController_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_join: {
        parameters: {
            query: {
                /** @description Raw invite token from the invite link */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CsrfController_getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_listAll: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"][];
                };
            };
        };
    };
    SubscriptionController_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreateRequestDto"];
            };
        };
        responses: {
            /** @description Subscription created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
            /** @description Invalid request or service unavailable */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description External service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_listMine: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of subscriptions for the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"][];
                };
            };
        };
    };
    SubscriptionController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubscriptionDeleteRequestDto"];
            };
        };
        responses: {
            /** @description Subscription cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request or unauthorized */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not subscribed to the service */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to delete external account */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPatchRequestDto"];
            };
        };
        responses: {
            /** @description Subscription updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
            /** @description No fields provided or invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription is not in a valid state for the transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_renew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription renewed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionPasswordResetDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Passwords do not match or account not provisioned */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description External service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscriptionController_setAutoRenew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionAutoRenewDto"];
            };
        };
        responses: {
            /** @description Auto-renew updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteController_list: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InviteResponseDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    InviteController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequestDto"];
            };
        };
        responses: {
            /** @description Invite token created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponseDto"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitePatchRequestDto"];
            };
        };
        responses: {
            /** @description Invite updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponseDto"];
                };
            };
            /** @description Invite not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsResponseDto"];
                };
            };
        };
    };
    UserController_listUsers: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResponseForAdminDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    UserController_getAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseForAdminDto"];
                };
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserDeleteRequestDto"];
            };
        };
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatchRequestDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseForAdminDto"];
                };
            };
        };
    };
    ServiceController_list: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ServiceResponseDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    ServiceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicePutRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponseDto"];
                };
            };
        };
    };
    ServiceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicePatchRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponseDto"];
                };
            };
        };
    };
    ServiceController_listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAccountResponseDto"][];
                };
            };
        };
    };
    OAuthProviderController_list: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OAuthProviderResponseDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    OAuthProviderController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthProviderPatchRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthProviderResponseDto"];
                };
            };
        };
    };
    LogController_list: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
                search?: string;
                createdBefore?: string;
                createdAfter?: string;
                logLevel?: "verbose" | "debug" | "log" | "warn" | "error" | "fatal";
                sessionId?: string;
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LogResponseDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    TaskController_listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConfigResponseDto"][];
                };
            };
        };
    };
    TaskController_updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskConfigDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConfigResponseDto"];
                };
            };
        };
    };
    TaskController_startTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConfigResponseDto"];
                };
            };
        };
    };
    TaskController_stopTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConfigResponseDto"];
                };
            };
        };
    };
    TaskController_runTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskConfigResponseDto"];
                };
            };
        };
    };
    SessionController_list: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminSessionResponseDto"][];
                        total: number;
                        hasMore: boolean;
                    };
                };
            };
        };
    };
    SessionController_getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionConfigResponseDto"];
                };
            };
        };
    };
    SessionController_updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionConfigDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionConfigResponseDto"];
                };
            };
        };
    };
    SessionController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsResponseDto"];
                };
            };
        };
    };
    ClientRouteController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_error: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminOAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminScheduledTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_adminSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRouteController_notFound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
